language: java
dist: xenial
sudo: false
jdk:
- oraclejdk8
node_js:
- 8.2.1
newman:
- 4.6.0
install:
- npm install newman
- npm install json-server
before_script:
- node --version
- npm --version
- ls -la node_modules
- node_modules/.bin/newman --version
- openssl aes-256-cbc -K $encrypted_36ed63dec190_key -iv $encrypted_36ed63dec190_iv -in application.yml.enc -out application.yml -d
script:
- "./.ci.sh"
- ls -l app/target
- cp app/target/sign*.jar .
- cd app/testsAPI && nohup node server.js &
- ./app/wait-for-it.sh -t 0 localhost:3000 -- echo "mock dailymotion is up"
- nohup java -jar sign*.jar --spring.profiles.active=default --app.file=app &
- ls -l
- ./app/wait-for-it.sh -t 0 localhost:8080 -- echo "signsatwork is up"
- node_modules/.bin/newman run app/testsAPI/User.postman_collection.json -e app/testsAPI/Local.postman_environment.json
- node_modules/.bin/newman run app/testsAPI/Community.postman_collection.json -e app/testsAPI/Local.postman_environment.json
- node_modules/.bin/newman run app/testsAPI/Favorite.postman_collection.json -e app/testsAPI/Local.postman_environment.json
- node_modules/.bin/newman run app/testsAPI/Request.postman_collection.json -e app/testsAPI/Local.postman_environment.json
- node_modules/.bin/newman run app/testsAPI/Sign.postman_collection.json -e app/testsAPI/Local.postman_environment.json
cache:
  directories: "$HOME/.m2"
before_deploy:
- export ARTEFACT=$(ls *.jar)
- echo Will deploy $ARTEFACT
deploy:
  provider: releases
  api_key:
    secure: XwFQS96AvxNX2W4F0DUVDVtwzmltkSmFeH3XUP8M9fThoLO6mVJOH47/GiouVFh2muyCv23Dz+w4qfzHgqIMyJiDO0TzP6Htq1QHVAulmZXYUP8lKvVo9oRm4cSIC0gwfpGJ5JPFA98vSVSDz2xMCN1mlzxVD2Lc2z0EKgKZEa4IfYQ0wftsYqAWeGVEGWAvimp96GDnxZqD00nI7J5zoR1DmgmAylBROMxP2qZCvyfb82x0FnhIleT8YnO0SWZ0/LV0qi6+mjTMzcAu2EnGB/XyOelNUK0EwEXtB4yB+W+oTHg4EShDE5zWiUcNESWBSe0BohNo3P2wwI4BghlQDFYFkTxxzjwqS5EFCqXgtXMJdEDIPlurbuBbxYfVi+40nlAnOQtCTYNmOTpdg4F+k4+DGt+ydZLkNlBGyZnucEnJGObmQu/CjcnuZa1mOZGon6R0hyk2ssTIFixKgCihwFdADn53eohEsStGbaN5j84bTfmIJ6YVFKaIPq+LWzLgnUxBtlZe0cofqrIChXMCTr0DZjvTKkZexyazLLJl6y65y8HZ0OxkdCsr9+MwdiCGxADBX/DOxr5Py3GmsHLkOu2aYOovtEpHGTPYjAvxN5bMeItfUjw91dfazEizl4k7eximS+pnUvWvtax21w4X9PXjPq07Zg7X9lq8xrvWcvU=
  file: "${ARTEFACT}"
  skip_cleanup: true
  on:
    tags: true
    repo: Orange-OpenSource/signs-at-work-social-network-dictionnary
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - denis.boisset@orange.com
