server.port: 8080
spring.datasource.url: jdbc:mysql://localhost:3306/signsatadis?serverTimezone=UTC
spring.datasource.username: asterix
spring.datasource.password: obelix
app.proxy.server: localhost
app.proxy.port : 3128
spring:
  jpa:
    show-sql: true

google.recaptcha.key.site: 6LeYxcYUAAAAAM5qEs0PFmVrx5u3M6uvtEX8ZAr-
google.recaptcha.key.secret: 6LeYxcYUAAAAAENkMr3oKHMGqqlhPI4U6R2qfxH2

app.admin.username: admin.signsatadis@adis-savoie.fr
app.manifest: "/manifest/signsatform/manifest.json"
app.name: "Signs@ADIS"
display-url: "/data/Presentation_Signs@Form.mp4"
spring.jpa.properties.hibernate.id.new_generator_mappings: false
app.url: "http://localhost:8080"

app.dailymotion_url:
app.dailymotion.grant_type: password
app.dailymotion.client_id: accfab055d184ff9bcf3
app.dailymotion.client_secret: 3dcd460d28d887fa25bc29c8031039a7edf52187
app.dailymotion.username: SignsAtWork
app.dailymotion.password: Decola1&

logging:
  config: classpath:logback-dev.xml