spring.profiles.active: dev

app.dailymotion.grant_type: password
app.dailymotion.client_id: accfab055d184ff9bcf3
app.dailymotion.client_secret: 3dcd460d28d887fa25bc29c8031039a7edf52187
app.dailymotion.username: SignsAtWork
app.dailymotion.password: Code56789&

app.admin.username: admin
app.admin.password: ?TelSignes!

---

spring.profiles: dev
server.port: 8080
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/signsatwork
spring.datasource.username: asterix
spring.datasource.password: obelix
app.proxy.server: localhost
app.proxy.port : 3128
spring:
  jpa:
    show-sql: true

google.recaptcha.key.site: 6LeYxcYUAAAAAM5qEs0PFmVrx5u3M6uvtEX8ZAr-
google.recaptcha.key.secret: 6LeYxcYUAAAAAENkMr3oKHMGqqlhPI4U6R2qfxH2

app.admin.username: admin@signsatwork.com
app.manifest: "/manifest/localhost/manifest.json"
app.name: "Signs@Work"
display-url: "https://www.dailymotion.com/embed/video/k2ADmPrk2ekIL2vU8hf"

---

spring.profiles: prod
server.port: 8080

spring.datasource.url: jdbc:mysql://localhost:3306/signsatwork
spring.datasource.username: asterix
spring.datasource.password: obelix
app.proxy.server: http-proxy.rd.francetelecom.fr
app.proxy.port : 8080

google.recaptcha.key.site: 6LeYxcYUAAAAAM5qEs0PFmVrx5u3M6uvtEX8ZAr-
google.recaptcha.key.secret: 6LeYxcYUAAAAAENkMr3oKHMGqqlhPI4U6R2qfxH2

app.admin.username: admin@signsatwork.com
app.manifest: "/manifest/signsatwork/manifest.json"
app.name: "Signs@Work"
display-url: "https://www.dailymotion.com/embed/video/k2ADmPrk2ekIL2vU8hf"

---

spring.profiles: form
server.port: 8079

spring.datasource.url: jdbc:mysql://localhost:3306/signsatform
spring.datasource.username: asterix
spring.datasource.password: obelix
app.proxy.server: http-proxy.rd.francetelecom.fr
app.proxy.port : 8080

google.recaptcha.key.site: 6LeYxcYUAAAAAM5qEs0PFmVrx5u3M6uvtEX8ZAr-
google.recaptcha.key.secret: 6LeYxcYUAAAAAENkMr3oKHMGqqlhPI4U6R2qfxH2

app.admin.username: admin@signsatform.com
app.manifest: "/manifest/signsatform/manifest.json"
app.name: "Signs@Form"
display-url: "https://www.dailymotion.com/embed/video/k2ADmPrk2ekIL2vU8hf"

---

spring.profiles: kermit-h2
server.port: 8443
app.proxy.server: proxy-internet.internal.fr
app.proxy.port : 3128

---

spring.profiles: kermit-mysql
server.port: 8443

spring.datasource.url: jdbc:mysql://localhost:3306/signsatwork
spring.datasource.username: asterix
spring.datasource.password: obelix

app.proxy.server: proxy-internet.internal.fr
app.proxy.port : 3128

---

spring.profiles: debug-https
server.port: 8443
app.proxy.server:
app.proxy.port :
server.ssl.key-store: debug-https-keystore.p12
server.ssl.key-store-password: password
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat

