server.port: 8080
spring.datasource.url: jdbc:mysql://localhost:3306/signsatadis?serverTimezone=UTC
spring.datasource.username: asterix
spring.datasource.password: obelix
app.proxy.server: localhost
app.proxy.port : 3128
spring:
  jpa:
    show-sql: true

google.recaptcha.key.site: 6LeYxcYUAAAAAM5qEs0PFmVrx5u3M6uvtEX8ZAr-
google.recaptcha.key.secret: 6LeYxcYUAAAAAENkMr3oKHMGqqlhPI4U6R2qfxH2

app.admin.username: admin.signsatadis@adis-savoie.fr
app.manifest: "/manifest/signsatform/manifest.json"
app.name: "Signs@ADIS"
display-url: "/data/Presentation_Signs@Form.mp4"
spring.jpa.properties.hibernate.id.new_generator_mappings: false
app.url: "http://localhost:8080"

logging:
  config: app/src/main/resources/logback-adis.xml
