spring.profiles: work
server.port: 8080

spring.datasource.url: jdbc:mysql://localhost:3306/signsatwork?serverTimezone=UTC
spring.datasource.username: asterix
spring.datasource.password: obelix
app.proxy.server: http-proxy.rd.francetelecom.fr
app.proxy.port : 8080

google.recaptcha.key.site: 6LeYxcYUAAAAAM5qEs0PFmVrx5u3M6uvtEX8ZAr-
google.recaptcha.key.secret: 6LeYxcYUAAAAAENkMr3oKHMGqqlhPI4U6R2qfxH2

app.admin.username: admin@signsatwork.com
app.manifest: "/manifest/signsatwork/manifest.json"
app.name: "Signs@Work"
display-url: "https://www.dailymotion.com/embed/video/k1gzhWGaCiQ1wcvU8hf"
spring.jpa.properties.hibernate.id.new_generator_mappings: false
app.url: "https://signsatwork.orange-labs.fr"
app.dailymotion_url: "https://api.dailymotion.com"
app.dailymotion.grant_type: password
app.dailymotion.client_id: accfab055d184ff9bcf3
app.dailymotion.client_secret: 3dcd460d28d887fa25bc29c8031039a7edf52187
app.dailymotion.username: SignsAtWork
app.dailymotion.password: Decola1&

logging:
  config: classpath:logback-work.xml
